# Generated by Django 5.0.4 on 2024-04-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='coffe_images/')),
            ],
        ),
    ]
